var antesdemorir_ideas =
[
  "Pasar Mario Bros al ritmo de la canción",
  "Leer tres libros que marquen tu vida",
  "Acampar dos noches en el bosque",
  "Hacer las paces con tus seres queridos",
  "Montar un león",
  "Montar a caballo",
  "Ir a un cmenterio a ver una película de fantasmas",
  "Dejarte llevar por un río, hasta el final",
  "Tomar un baño de lodo",
  "Lanzarte de la tirolesa",
  "Ir a un concierto de Heavy Mettal",
  "Escribir un final alternativo para Death Note",
  "Ver Death Note",
  "Escribir un diario de pesadillas",
  "Escribir un diario de sueños",
  "Escribir una historia de terror que ponga los pelos de punta",
  "Leer 'ESO', el libro en el que se basó la película",
  "Correr un maratón",
  "Terminar una carrera universitaria",
  "Tener una foto en la Torre Eifel",
  "Aprender a programar",
  "Volar una avioneta",
  "Lanzarte en parapente",
  "Aventarte del bungee",
  "Sobrevivir una semana en la Amazonía",
  "Invitar a comer a tu casa a una persona de la calle",
  "Aprender a tocar una pieza en el piano",
  "Leer un libro a un ciego",
  "Escalar el Monte Everest.",
  "Visitar la granja de Emily Rose.",
  "Actuar de extra en una película",
  "Hacer una parada de manos",
  "Poner helado de vainilla en un frasco de mostaza y salir con él a la calle para comerlo mientras todos te observan."
]
