var antesdemorir_ideas =
[
  "Pasar Mario Bros al ritmo de la canción",
  "Leer tres libros que marquen tu vida",
  "Acampar dos noches en el bosque",
  "Hacer las paces con tus seres queridos",
  "Montar un león",
  "Montar a caballo",
  "Ir a un cmenterio a ver una película de fantasmas",
  "Dejarte llevar por un río, hasta el final",
  "Tomar un baño de lodo",
  "Lanzarte de la tirolesa",
  "Ir a un concierto de Heavy Mettal",
  "Escribir un final alternativo para Death Note",
  "Ver Death Note",
  "Escribir un diario de pesadillas",
  "Escribir un diario de sueños",
  "Escribir una historia de terror que ponga los pelos de punta",
  "Leer 'ESO', el libro en el que se basó la película",
  "Correr un maratón",
  "Terminar una carrera universitaria",
  "Tener una foto en la Torre Eifel",
  "Aprender a programar",
  "Volar una avioneta",
  "Lanzarte en parapente",
  "Aventarte del bungee",
  "Sobrevivir una semana en la Amazonía",
  "Invitar a comer a tu casa a una persona de la calle",
  "Aprender a tocar una pieza en el piano",
  "Leer un libro a un ciego",
  "Escalar el Monte Everest.",
  "Visitar la granja de Emily Rose.",
  "Actuar de extra en una película",
  "Hacer una parada de manos",
  "Poner helado de vainilla en un frasco de mostaza y salir con él a la calle para comerlo mientras todos te observan.",
  "Bucear en un arrecife de Sudáfrica",
  "Volar en gravedad cero",
  "No afeitarte durante un año",
  "Hacer una película casera",
  "Escalar una montaña",
  "Inventa tu propio paso de baile",
  "Visitar los siete continentes",
  "Cruzar tu país en bicicleta",
  "Participar en el carnaval de Brasil",
  "Bailar tango en Argentina",
  "Surfear",
  "Bucear",
  "Trabajar un mes como voluntario",
  "Subir a un volcán activo",
  "Navegar en velero",
  "Pasar una semana a solas en la selva",
  "Asistir a un festival de música en otro país",
  "Asistir a los juegos Olímpicos",
  "Participar de la ceremiona del té de la cultura japonesa",
  "Ver pingüinos en el polo sur",
  "Ver osos en el polo norte",
  "Disfrutar de un habano en Cuba",
  "Visitar todas las capitales europeas",
  "Comer en todas las ciudades latinoamericanas",
  "Probar la cajeta mexicana",
  "Probar el dulce de leche argentino",
  "Cruzar un océano en un yate",
  "Viajar a Alaska",
  "Tomar vodka con rusos",
  "Comer escorpión en China",
  "Ver el Taj Mahal en la India",
  "Montar en camello",
  "Pintar un grafiti",
  "Hacer una corta película o video para Youtube",
  "No pagar una comida que no te guste",
  "Visitar las pirámides de Egipto",
  "Mirar un eclipse lunar",
  "Adoptar un perrito callejero"
]
